const contentLabelsEu = {
  algebra: "Aljebra lineala",
  "algebra.matrices": "Matrizeak",
  "algebra.matrices.tipos": "Motak, dimentsioa eta berdintasuna",
  "algebra.matrices.operaciones": "Batuketa eta eskalar bidezko biderketa",
  "algebra.matrices.producto": "Matrizeen biderketa",
  "algebra.matrices.potencias": "Matrizeen berreturak",
  "algebra.matrices.identidad": "Matrize identitatea",
  "algebra.matrices.inversa": "Alderantzizko matrizea",
  "algebra.matrices.ecuaciones": "Ekuazio matrizialak",
  "algebra.matrices.rango": "Matrize baten heina",
  "algebra.matrices.parametros": "Parametrodun matrizeak",
  "algebra.determinantes": "Determinanteak",
  "algebra.determinantes.orden": "2. eta 3. ordenako determinanteak",
  "algebra.determinantes.menores": "Minoreak eta kofaktoreak",
  "algebra.determinantes.laplace": "Laplaceren garapena",
  "algebra.determinantes.propiedades": "Determinanteen propietateak",
  "algebra.determinantes.invertibilidad": "Determinantea eta alderantzikagarritasuna",
  "algebra.determinantes.inversa": "Alderantzizkoaren kalkulua",
  "algebra.determinantes.rango": "Determinantea eta heina",
  "algebra.determinantes.parametros": "Parametrodun determinanteak",
  "algebra.sistemas": "Ekuazio linealen sistemak",
  "algebra.sistemas.matricial": "Adierazpen matriziala",
  "algebra.sistemas.gauss": "Gaussen metodoa",
  "algebra.sistemas.cramer": "Cramerren erregela",
  "algebra.sistemas.rouche": "Rouché-Frobeniusen teorema",
  "algebra.sistemas.parametros": "Parametroen araberako eztabaida",
  "algebra.sistemas.modelizacion": "Problemak eta modelizazioa",
  analisis: "Analisia",
  "analisis.funciones": "Funtzioak",
  "analisis.funciones.dominio": "Definizio-eremua, irudi-multzoa eta simetriak",
  "analisis.funciones.operaciones": "Eragiketak eta konposizioa",
  "analisis.funciones.inversa": "Alderantzizko funtzioa",
  "analisis.funciones.elementales": "Oinarrizko funtzioak",
  "analisis.limites": "Limiteak eta jarraitutasuna",
  "analisis.limites.calculo": "Limiteen kalkulua",
  "analisis.limites.indeterminaciones": "Indeterminazioak",
  "analisis.limites.laterales": "Albo-limitak eta limite infinituak",
  "analisis.limites.asintotas": "Asintotak",
  "analisis.limites.continuidad": "Jarraitutasuna",
  "analisis.limites.teoremas": "Jarraitutasun-teoremak",
  "analisis.derivadas": "Deribatuak",
  "analisis.derivadas.definicion": "Definizioa eta interpretazio geometrikoa",
  "analisis.derivadas.reglas": "Deribazio-arauak",
  "analisis.derivadas.tangente": "Zuzen ukitzailea eta normala",
  "analisis.derivadas.derivabilidad": "Deribagarritasuna",
  "analisis.derivadas.lhopital": "L’Hôpitalen erregela",
  "analisis.estudio": "Funtzioen azterketa eta optimizazioa",
  "analisis.estudio.crecimiento": "Monotonia eta muturrak",
  "analisis.estudio.concavidad": "Ahurtasuna eta inflexioa",
  "analisis.estudio.representacion": "Adierazpen grafiko osoa",
  "analisis.estudio.teoremas": "Rolleren eta batez besteko balioaren teoremak",
  "analisis.estudio.optimizacion": "Optimizazio-problemak",
  "analisis.integrales": "Integralak",
  "analisis.integrales.inmediatas": "Berehalako primitiboak",
  "analisis.integrales.sustitucion": "Aldagai-aldaketa",
  "analisis.integrales.partes": "Zatikako integrazioa",
  "analisis.integrales.racionales": "Funtzio arrazionalak",
  "analisis.integrales.definida": "Integral definitua eta Barrowen erregela",
  "analisis.aplicaciones-integral": "Integralaren aplikazioak",
  "analisis.aplicaciones-integral.bajo-curva": "Kurba baten azpiko azalera",
  "analisis.aplicaciones-integral.entre-curvas": "Kurben arteko azalera",
  "analisis.aplicaciones-integral.recintos": "Esparru mugatuak",
  "analisis.aplicaciones-integral.volumenes": "Biraketa-bolumenak",
  geometria: "Espazioko geometria",
  "geometria.vectores": "Bektoreak",
  "geometria.vectores.operaciones": "Eragiketak eta mendekotasun lineala",
  "geometria.vectores.escalar": "Biderkadura eskalarra",
  "geometria.vectores.vectorial": "Biderkadura bektoriala",
  "geometria.vectores.mixto": "Biderkadura mistoa",
  "geometria.rectas-planos": "Zuzenak eta planoak",
  "geometria.rectas-planos.recta": "Zuzenaren ekuazioak",
  "geometria.rectas-planos.plano": "Planoaren ekuazioak",
  "geometria.rectas-planos.posiciones": "Posizio erlatiboak",
  "geometria.rectas-planos.intersecciones": "Ebakidurak",
  "geometria.rectas-planos.parametros": "Parametrodun problemak",
  "geometria.metrica": "Geometria metrikoa",
  "geometria.metrica.angulos": "Angeluak",
  "geometria.metrica.distancias": "Distantziak",
  "geometria.metrica.perpendicularidad": "Perpendikulartasuna",
  "geometria.metrica.proyecciones": "Proiekzioak",
  "geometria.metrica.simetria": "Simetriak",
  "geometria.metrica.areas-volumenes": "Azalerak eta bolumenak",
  probabilidad: "Probabilitatea",
  "probabilidad.sucesos": "Probabilitatea",
  "probabilidad.sucesos.operaciones": "Gertaeren arteko eragiketak",
  "probabilidad.sucesos.condicionada": "Probabilitate baldintzatua",
  "probabilidad.sucesos.independencia": "Independentzia",
  "probabilidad.sucesos.diagramas": "Taulak eta zuhaitz-diagramak",
  "probabilidad.sucesos.total": "Probabilitate osoa",
  "probabilidad.sucesos.bayes": "Bayesen teorema",
  "probabilidad.variables": "Aldagai ausazkoak",
  "probabilidad.variables.tipos": "Aldagai diskretuak eta jarraituak",
  "probabilidad.variables.funciones": "Probabilitate-funtzioak",
  "probabilidad.variables.esperanza": "Itxaropena",
  "probabilidad.variables.varianza": "Bariantza eta desbideratze tipikoa",
  "probabilidad.distribuciones": "Banaketak",
  "probabilidad.distribuciones.binomial": "Banaketa binomiala",
  "probabilidad.distribuciones.normal": "Banaketa normala",
  "probabilidad.distribuciones.tipificacion": "Tipifikazioa",
  "probabilidad.distribuciones.aproximacion": "Binomialaren hurbilketa normalaren bidez",
};
